// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "@/app/providers";
import "../styles/globals.css";
import { Toaster } from "sonner";
import Background from "@/components/background";
import ChatFab from "@/components/chat/ChatFab";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* 👇 Thêm suppressHydrationWarning để tránh cảnh báo body */}
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        {/* Nền 3D client-only (file này đã có "use client" + mounted guard) */}
        <Background />

        <Providers>
          <div className="relative z-10">
            {children}
            <Toaster richColors position="top-right" />
          </div>

          {/* Nút chat client-only */}
          <ChatFab />
        </Providers>
      </body>
    </html>
  );
}
